apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti
  template:
    metadata:
      labels:
        app: olivetti
    spec:
      containers:
      - name: olivetti-container
        image: kdasofficial/olivetti-app:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: olivetti-service
spec:
  selector:
    app: olivetti
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000